### ISSUE TITLE
App creation fails

### ISSUE THREAD

**Issue by assimovt** [cawfree/create-react-native-dapp#10]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

I've logged into Expo and ran the npx command as instructed:

```
npx create-react-native-dapp
```

It then prompted for the project details and bailed out with the error:

```
Cannot determine which native SDK version your project uses because the module `expo` is not installed. Please install it with `yarn add expo` and try again.
```

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

* *Node version*: v14.15.5
* *Expo version (installed globally)* : 4.8.1

Initializing a standalone expo project (bare/managed) otherwise works.

Here is the log:

```
  Ξ Welcome to create-react-native-dapp! Ξ
     Your next Ethereum application starts here.

✔ What is your app named? … my-react-dapp
✔ What is the iOS bundle identifier? … com.myreactdapp
✔ What is the Android package name? … com.myreactdapp
✔ What is the URI scheme? … myreactdapp
Creating a new React Native app in /Users/user/code/my-react-dapp.

Using package manager as yarnpkg with yarn interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

yarn add v1.22.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-native-scripts > babel-runtime > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 20 new dependencies.
info Direct dependencies
└─ react-native-scripts@2.0.1
info All dependencies
├─ ansi-styles@3.2.1
├─ babel-runtime@6.26.0
├─ chalk@2.4.2
├─ color-convert@1.9.3
├─ color-name@1.1.3
├─ core-js@2.6.12
├─ cross-spawn@5.1.0
├─ escape-string-regexp@1.0.5
├─ has-flag@3.0.0
├─ isexe@2.0.0
├─ lru-cache@4.1.5
├─ minimist@1.2.5
├─ pseudomap@1.0.2
├─ react-native-scripts@2.0.1
├─ regenerator-runtime@0.11.1
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ supports-color@5.5.0
├─ which@1.3.1
└─ yallist@2.1.2
✨  Done in 3.37s.
(node:76872) UnhandledPromiseRejectionWarning: Error: Cannot find module '/Users/user/code/my-react-dapp/node_modules/react-native-scripts/build/scripts/init.js'
Require stack:
- /usr/local/lib/node_modules/create-react-native-app/build/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at _callee2$ (/usr/local/lib/node_modules/create-react-native-app/build/index.js:128:32)
    at tryCatch (/usr/local/lib/node_modules/create-react-native-app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/create-react-native-app/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/usr/local/lib/node_modules/create-react-native-app/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/create-react-native-app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/create-react-native-app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
(Use `node --trace-warnings ...` to show where the warning was created)
(node:76872) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:76872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[00:54:28] Cannot determine which native SDK version your project uses because the module `expo` is not installed. Please install it with `yarn add expo` and try again.
[00:54:28]     ├─ getExpoSDKVersion /Users/user/.nvm/versions/node/v14.15.5/lib/node_modules/expo-cli/node_modules/@expo/config/src/Project.ts:23:9
    ├─ ensureConfigHasDefaultValues /Users/user/.nvm/versions/node/v14.15.5/lib/node_modules/expo-cli/node_modules/@expo/config/src/Config.ts:480:18
    ├─ fillAndReturnConfig /Users/user/.nvm/versions/node/v14.15.5/lib/node_modules/expo-cli/node_modules/@expo/config/src/Config.ts:104:10
    ├─ getConfig /Users/user/.nvm/versions/node/v14.15.5/lib/node_modules/expo-cli/node_modules/@expo/config/src/Config.ts:189:10
    ├─ actionAsync /Users/user/.nvm/versions/node/v14.15.5/lib/node_modules/expo-cli/src/commands/ejectAsync.ts:29:19
    ├─ /Users/user/.nvm/versions/node/v14.15.5/lib/node_modules/expo-cli/src/commands/utils/profileMethod.ts:16:21
    ├─ /Users/user/.nvm/versions/node/v14.15.5/lib/node_modules/expo-cli/src/commands/utils/applyAsyncAction.ts:12:12
    └─ expo eject /Users/user/.nvm/versions/node/v14.15.5/lib/node_modules/expo-cli/src/exp.ts:348:7
(node:76869) UnhandledPromiseRejectionWarning: Error: Command failed: expo eject --non-interactive
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at ejectExpoProject (/Users/user/.npm/_npx/76869/lib/node_modules/create-react-native-dapp/build/main/buidler/index.js:61:21)
    at Object.create (/Users/user/.npm/_npx/76869/lib/node_modules/create-react-native-dapp/build/main/buidler/index.js:726:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/user/.npm/_npx/76869/lib/node_modules/create-react-native-dapp/build/main/cli/index.js:115:33
(Use `node --trace-warnings ...` to show where the warning was created)
(node:76869) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:76869) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cawfree** [comment]
Hello, can you verify what version of `expo-cli` you have installed?

**Comment by assimovt** [comment]
Yeah, appeared to be a problem with Expo installation. I've removed globally installed expo, reinstalled, and things started to work 👍
