### ISSUE TITLE
Unable to successfully create project

### ISSUE THREAD

**Issue by MarkOSullivan94** [cawfree/create-react-native-dapp#21]
- **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question about the decisions made in the repository
  - [ ] question about how to use this project

- **Summary**

1. Followed the instructions contained within the `To get started` section
2. Executed `npx create-react-native-dapp`
3. Enter app name & URI scheme (sticking to the defaults)
4. After getting instructions on how to run project error message appears immediately after `npm run web` instruction

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Error message is shown below

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-test-renderer@17.0.1
npm ERR! node_modules/react-test-renderer
npm ERR!   dev react-test-renderer@"17.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/mos/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mos/.npm/_logs/2021-11-03T17_07_35_566Z-debug.log
node:child_process:707
    err = new Error(msg);
          ^

Error: Command failed: npm i
    at checkExecSyncError (node:child_process:707:11)
    at Object.execSync (node:child_process:744:15)
    at shouldInstall (/Users/mos/.npm/_npx/1064147bb9e7ae50/node_modules/create-react-native-dapp/build/main/buidler/index.js:534:48)
    at Object.create (/Users/mos/.npm/_npx/1064147bb9e7ae50/node_modules/create-react-native-dapp/build/main/buidler/index.js:777:5)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /Users/mos/.npm/_npx/1064147bb9e7ae50/node_modules/create-react-native-dapp/build/main/cli/index.js:119:33 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 67961,
  stdout: null,
  stderr: null
}
```

**Comment by cawfree** [comment]
Hey @MarkOSullivan94, thanks for raising. May I check:
  - the behaviour you're seeing is any different if you use `yarn web`?
  - the `npx create-react-native-dapp` command completed successfully, and wasn't terminated early?

**Comment by MarkOSullivan94** [comment]
Hey @cawfree thanks for the reply! 

The `npx create-react-native-dapp` command didn't complete successfully and was terminated early because of the error above, I didn't execute `npm run web` sorry for confusion!

See screenshot below

<img width="709" alt="Screenshot 2021-11-04 at 22 10 54" src="https://user-images.githubusercontent.com/6950843/140420640-444f2060-e2b3-4ca4-bae4-450cbb5ac29c.png">

**Comment by sergey-king** [comment]
Same issue
<img width="1029" alt="Screen Shot 2021-11-21 at 11 12 41 AM" src="https://user-images.githubusercontent.com/48575848/142769826-a2428fd5-b81a-4c16-85ee-3ab54e8a8f2c.png">

**Comment by sergey-king** [comment]
> 

I think our problem is that we're on react@^17.0.1 and the project is configured with react16 specifically the problem part is "enzyme-adapter-react-16": "1.15.6", dependency. I found an unofficial https://www.npmjs.com/package/@wojtekmaj/enzyme-adapter-react-17 alternative but wasn't able to make it work yet. LMK if you find a solution

**Comment by sergey-king** [comment]
@cawfree @simibac would love some help on this guys. Awesome project

**Comment by sergey-king** [comment]
Found the problem. Default installer uses Yarn by default and for some reason doesn't work with npm.
Just install Yarn and it will work @MarkOSullivan94

**Comment by MarkOSullivan94** [comment]
Thanks for the reply @sergey-king!

Should I close this or should I keep it open until it works for npm?
