### ISSUE TITLE
App not working on expo production mode

### ISSUE THREAD

**Issue by francesco-clementi-92** [cawfree/create-react-native-dapp#25]
- **I'm submitting a ...**
  [X] bug report

The app doesn't work on minified/production code.

Step:

1. create a new app
2. run expo start --no-dev
3. try to open web/android/ios it will not start
4. if you digit w on console, it will show the real error

```
C:\my-react-dapp\node_modules\metro-hermes-compiler\src\emhermesc.js:81
          throw ex;
          ^

RuntimeError: abort(TypeError: Cannot read properties of undefined (reading 'before')). Build with -s ASSERTIONS=1 for more info.        
    at process.abort (C:\cry\my-react-dapp\node_modules\metro-hermes-compiler\src\emhermesc.js:796:13)
    at process.emit (node:events:390:28)
    at process.emit (C:\Users\cico\AppData\Roaming\npm\node_modules\expo-cli\node_modules\source-map-support\source-map-support.js:439:21)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
```

Please any idea on how to run the app in production mode?

**Comment by francesco-clementi-92** [comment]
I also tried to downgrade expo, but same error on different location

**Comment by cawfree** [comment]
This project is ejected from expo, so I believe we wouldn't be able to expect it to work with just the `expo start` command.

Does it work as expected when you run `yarn ios`/`yarn android`?

**Comment by SamanthaSHan** [comment]
Actually, it does work with expo start -- at least for connecting the wallet.
