### ISSUE TITLE
Bad output from running the command

### ISSUE THREAD

**Issue by lub0s** [cawfree/create-react-native-dapp#36]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
After running the create app the generated output doesn't match the expected format defined in the builders folder. I uploaded the output at https://github.com/lub0s/crnd-error. Also see attached stacktrace. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

OS: macOS Monterey 12.3.1 
Node: 18.2.0
Stacktrace from running create app:
```
npx create-react-native-dapp

  MMMMMMMMMMMMMMMMMMMMMMMXkkKMMMMMMMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMMMMMWKd;':OWMMMMMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMMMMW0dl;..,kNMMMMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMMMNOdol;...,dNMMMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMMXkdool,....'lXMMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMWXxoc:;,.......c0WMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMKl;,'....     ..:0MMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMKxl:'....    .,:oKMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMWXOkxoc,...;cclo0WMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMWXkdxkxoclc;,lKWMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMMMN0doo:'..;xNMMMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMMMMWKko;.'c0WMMMMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMMMMMMNOl:dXMMMMMMMMMMMMMMMMMMMMMM
  MMMMMMMMMMMMMMMMMMMMMMMWXXNMMMMMMMMMMMMMMMMMMMMMMM

      Ξ Welcome to create-react-native-dapp! Ξ
     Your next Ethereum application starts here.

✔ What is your app named? … CoinbaseWalletTest4
✔ What is the URI scheme? … coinbaseee
✔ Downloaded and extracted project files.

Using npm to install packages.

✔ Installed JavaScript dependencies.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following npm commands.

- cd CoinbaseWalletTest4
- npm run android
- npm run ios
- npm run web
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: coinbasewallettest@1.0.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0-0" from enzyme-adapter-react-16@1.15.6
npm ERR! node_modules/enzyme-adapter-react-16
npm ERR!   dev enzyme-adapter-react-16@"1.15.6" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/lubosmudrak/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lubosmudrak/.npm/_logs/2022-05-26T10_15_58_404Z-debug-0.log
node:internal/errors:845
  const err = new Error(message);
              ^

Error: Command failed: npm i
    at checkExecSyncError (node:child_process:817:11)
    at Object.execSync (node:child_process:888:15)
    at shouldInstall (/Users/lubosmudrak/.npm/_npx/1064147bb9e7ae50/node_modules/create-react-native-dapp/build/main/buidler/index.js:534:48)
    at Object.create (/Users/lubosmudrak/.npm/_npx/1064147bb9e7ae50/node_modules/create-react-native-dapp/build/main/buidler/index.js:777:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/lubosmudrak/.npm/_npx/1064147bb9e7ae50/node_modules/create-react-native-dapp/build/main/cli/index.js:119:33 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 13995,
  stdout: null,
  stderr: null
}

Node.js v18.2.0
```

**Comment by hiteshjoshi1** [comment]
I have the exact same issue and I am on node v14.17.4
in the error log I see
`98 error ERESOLVE unable to resolve dependency tree
99 error
100 error While resolving: my-react-dapp@1.0.0
100 error Found: react@17.0.1
100 error node_modules/react
100 error   react@"17.0.1" from the root project
100 error
100 error Could not resolve dependency:
100 error peer react@"^16.0.0-0" from enzyme-adapter-react-16@1.15.6
100 error node_modules/enzyme-adapter-react-16
100 error   dev enzyme-adapter-react-16@"1.15.6" from the root project
`

**Comment by ink-paint** [comment]
I can run with node16.15.1
