### ISSUE TITLE
npx create-react-native-app dapp -t with-typescript not working

### ISSUE THREAD

**Issue by shin101004** [cawfree/create-react-native-dapp#40]
- **I'm submitting a ...**
  [V] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

I want to use @walletconnect/react-native-dapp. so, i installed create-react-native-dapp pacakges. it failed.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
✖ Something went wrong in downloading and extracting the project files.
node:internal/errors:863
  const err = new Error(message);
              ^

Error: Command failed: npx create-react-native-app dapp -t with-typescript
    at checkExecSyncError (node:child_process:871:11)
    at Object.execSync (node:child_process:943:15)
    at createBaseProject (/Users/jerry/.npm/_npx/1064147bb9e7ae50/node_modules/create-react-native-dapp/build/main/buidler/index.js:46:57)
    at Object.create (/Users/jerry/.npm/_npx/1064147bb9e7ae50/node_modules/create-react-native-dapp/build/main/buidler/index.js:759:5)
    at /Users/jerry/.npm/_npx/1064147bb9e7ae50/node_modules/create-react-native-dapp/build/main/cli/index.js:119:49
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 31528,
  stdout: null,
  stderr: null
}

Node.js v18.12.1

**Comment by blixit** [comment]
I'm getting the same issue when installing `create-react-native-app@3.8.0`

```
node v19.3.0
npm 9.2.0
```

The issue comes from create-react-native-app was already reported here: [create-react-native-app](https://github.com/expo/create-react-native-app/issues/917)

<img width="488" alt="image" src="https://user-images.githubusercontent.com/6025710/216064118-ce26fc9e-3c21-45f2-bf6a-395074037231.png">

EDIT
https://github.com/expo/create-react-native-app/issues/917#issuecomment-1412239393
