### ISSUE TITLE
`npx create-react-native-dapp` errors out

### ISSUE THREAD

**Issue by collinglass** [cawfree/create-react-native-dapp#5]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
`npx create-react-native-dapp` errors out:

```
[21:20:44] Error: Problems validating fields in app.json. See https://docs.expo.io/versions/v40.0.0/workflow/configuration/
[21:20:44]  • is missing required property 'name'.
[21:20:44]  • is missing required property 'slug'.
Warning! Your git working tree is dirty.
It's recommended to commit all your changes before proceeding,
so you can revert the changes made by this command if necessary.

[21:20:44] Input is required, but Expo CLI is in non-interactive mode.
Please specify eject method (bare, expokit) with the --eject-method option.
(node:9459) UnhandledPromiseRejectionWarning: Error: Command failed: cd /Users/foobar/.../my-react-dapp; expo eject --non-interactive;
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at ejectExpoProject (/Users/collinglass/.npm/_npx/9459/lib/node_modules/create-react-native-dapp/build/main/buidler/index.js:61:21)
    at Object.create (/Users/collinglass/.npm/_npx/9459/lib/node_modules/create-react-native-dapp/build/main/buidler/index.js:720:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/foobar/.npm/_npx/9459/lib/node_modules/create-react-native-dapp/build/main/cli/index.js:115:33
(node:9459) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9459) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
111
```

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Using nvm on mac, tried with node v12.20.0 and v13.12.0, same error.

**Comment by cawfree** [comment]
Hi @collinglass, thanks for raising this issue? Can I confirm you've logged into the [Expo CLI](https://docs.expo.io/workflow/expo-cli/)?

**Comment by collinglass** [comment]
Yes I am, just reverified that

**Comment by cawfree** [comment]
Just to confirm, by using all of the default parameters suggested by the CLI, the project seems to initialize correctly.

Are you specifying any custom parameters to the CLI? By the way, have you checked out [this](https://github.com/cawfree/create-react-native-dapp/issues/2) similar issue?

**Comment by collinglass** [comment]
figured it out, outdated expo version. My bad, closing.

**Comment by cawfree** [comment]
@collinglass Great to hear you found a solution! Best of luck.
